language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.4
      env: setup=lowest
    - php: 5.5
      env: setup=stable

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit
