#!/usr/bin/env php
<?php

use Arrilot\DataAnonymization\Commands\RunCommand;
use Arrilot\DataAnonymization\Anonymizer;
use Symfony\Component\Console\Application;

require './vendor/autoload.php';

$dsn = 'mysql:dbname=test;host=127.0.0.1';
$user = 'testuser';
$password = 'test*';

$anonymizer = new Anonymizer($dsn, $user, $password);

$app = new Application('Data Anonymization');
$app->add(new RunCommand($anonymizer));
$app->run();
